import { Body, Controller, Get, Post, Query } from '@nestjs/common';
import { IsBoolean, IsNotEmpty, IsOptional, IsString } from 'class-validator';
import { PlansService } from '../plans/plans.service';

class ReceiptDto {
  @IsString()
  @IsNotEmpty()
  assignmentId: string;

  /** Idempotency key generated by the node agent for this apply attempt. */
  @IsString()
  @IsNotEmpty()
  receiptKey: string;

  @IsBoolean()
  ok: boolean;

  @IsOptional()
  @IsString()
  fingerprint?: string;

  @IsOptional()
  @IsString()
  error?: string;
}

/**
 * Endpoints polled/called by node agents (the local simulator implements this
 * protocol). The platform never pushes into nodes; agents pull work and post
 * receipts, which keeps private key material off this system entirely.
 */
@Controller('api/agent')
export class AgentController {
  constructor(private readonly plans: PlansService) {}

  @Get('poll')
  poll(@Query('node') node: string) {
    return this.plans.pollForNode(node);
  }

  @Post('receipt')
  receipt(@Query('node') node: string, @Body() dto: ReceiptDto) {
    return this.plans.submitReceipt(node, dto);
  }
}
